[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  VITE_API_URL = "https://learnify-render-backend.onrender.com/api"
  VITE_BACKEND_URL = "https://learnify-render-backend.onrender.com"

# Handle SPA routing by redirecting all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 